# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20161025_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
