# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_auto_20161010_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='queries.Entry')),
            ],
        ),
    ]
