# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inheritance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('-age',)},
        ),
    ]
