# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 08:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 10, 8, 44, 18, 678950, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
