# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20161017_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
