# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20161017_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeuser',
            name='username',
            field=models.CharField(max_length=10),
        ),
    ]
