# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20161111_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocomment',
            name='photo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='photo.Photo'),
            preserve_default=False,
        ),
    ]
