# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_myuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='이메일'),
        ),
    ]
