# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_coffee_major_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coffee',
        ),
        migrations.RemoveField(
            model_name='major',
            name='id',
        ),
        migrations.AddField(
            model_name='major',
            name='num',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='major',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
