# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyStudent',
            fields=[
            ],
            options={
                'ordering': ('-year',),
                'proxy': True,
            },
            bases=('person.student',),
        ),
    ]
