# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 08:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20161110_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='following_users',
            field=models.ManyToManyField(related_name='follower_users', through='member.Following', to=settings.AUTH_USER_MODEL),
        ),
    ]
