# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20161007_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='invite_reason',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
