# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20161007_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
