# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photocomment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototag',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
