# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_following_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='following_users',
            field=models.ManyToManyField(related_name='followers', through='member.Following', to=settings.AUTH_USER_MODEL),
        ),
    ]
